name:   trodotest
recipe: symfony
config:
    php:              '8.2'
    via:              nginx
    webroot:          public
    database:         mysql:8.0
    xdebug:           true
    composer:         []
    composer_version: '2.6.2'

proxy:
    phpmyadmin:
        - pma.trodotest.lndo.site

services:
    appserver:
        build:
            - echo 'alias ll="ls -la"' >> /var/www/.bashrc
        build_as_root:
            - docker-php-ext-install sockets
            - docker-php-ext-enable sockets
        overrides:
            environment:
                PHP_IDE_CONFIG: "serverName=appserver"
                XDEBUG_SESSION_START: lando
                XDEBUG_CONFIG:        "discover_client_host=0 client_host=host.docker.internal"
                SSH_AUTH_SOCK:        /run/host-services/ssh-auth.sock
        run_as_root:
            - chown www-data:www-data /run/host-services/ssh-auth.sock
            - chmod g+w /run/host-services/ssh-auth.sock

    database:
        type: mysql:8.0
        config:
            database: config/lando/mysql-server.cnf

    node:
        type: node:18
        build:
            - npm install
            - npm run dev

    phpmyadmin:
        type: phpmyadmin:5.1
        hosts:
            - database

    mailhog:
        type:        mailhog:v1.0.0
        portforward: true
        hogfrom:
            - appserver

keys: false

tooling:
    npm:
        service: node
    node:
        service: node
    dep:
        service: appserver
        cmd:     php vendor/bin/dep